import { useState } from 'react';
import Head from 'next/head';

export default function Home() {
  const [username, setUsername] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Finances</h1>

        <h2>Create User</h2>

        <form action="">
          <div className="form-control">
            <label htmlFor="username">Username</label>
            <input id="username" type="text" name="username" />
          </div>

          <div className="form-control">
            <input type="submit" value="Submit" />
          </div>
        </form>
      </main>
    </>
  );
}
