import { useState } from 'react';
import Head from 'next/head';
import { API, graphqlOperation } from 'aws-amplify';
import * as mutations from '../src/graphql/mutations';

export default function Home() {
  const [username, setUsername] = useState('');

  const handleSubmit = async (event) => {
    event.preventDefault();

    const user = { name: username };

    const newUser = await API.graphql({
      query: mutations.createBlog,
      variables: {
        input: user,
      },
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Finances</h1>

        <h2>Create User</h2>

        <form onSubmit={handleSubmit}>
          <div className="form-control">
            <label htmlFor="username">Username</label>
            <input id="username" type="text" name="username" value={username} onChange={(event) => setUsername(event.target.value)} required />
          </div>

          <div className="form-control">
            <input type="submit" value="Submit" />
          </div>
        </form>
      </main>
    </>
  );
}
